### ISSUE TITLE
WowneroX Logo (5,000 WOWX)

### ISSUE THREAD

**Issue by wownerox** [wownerox/meta#5]

**Comment by lalanza808** [comment]
@cismee

**Comment by cismee** [comment]
hello

**Comment by wownerox** [comment]
hi @cismee Thanks for the logo! Please DM AVAX address.

**Comment by cismee** [comment]
![WOWX_Logo](https://user-images.githubusercontent.com/43832741/146173539-85623476-b2b1-44b2-a1a1-ca4a975152e0.png)

https://wownero.net/WOWX_Logo.svg
