### ISSUE TITLE
Web App for users to anonymously post locked WOW transaction data (15,000 WOWX)

### ISSUE THREAD

**Issue by wownerox** [wownerox/meta#6]
**page 1**

- users can submit TXID, TXKEY, address, and AVAX address in a simple form
- data is saved to a database

**page 2**

- users can see a table of all TXIDs, locked WOW amounts, unlock times
- app will make [get_transactions](https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#get_transactions) and  [check_tx_key](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#check_tx_key) RPC calls to gather and verify information
- app will display the total funds that have been locked

**Comment by XfedeX** [comment]
I'm currently working on this.
